// Generated by CoffeeScript 1.10.0
(function() {
    var logger, winston;

    winston = require('winston');

    logger = new winston.Logger({
        transports: [new winston.transports.Console({})],
        exitOnError: false
    });

    module.exports = logger;

}).call(this);
